# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\x12\x06\x65vents\"\xa1\x01\n\x05\x45vent\x12\x11\n\tflight_id\x18\x01 \x01(\t\x12\x0c\n\x04seat\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x15\n\rcustomer_name\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x16\n\x0epayment_method\x18\x06 \x01(\t\x12\x18\n\x10reservation_time\x18\x07 \x01(\t\x12\r\n\x05price\x18\x08 \x01(\t\"\x16\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t27\n\x0c\x45ventService\x12\'\n\tSendEvent\x12\r.events.Event\x1a\x0b.events.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENT']._serialized_start=24
  _globals['_EVENT']._serialized_end=185
  _globals['_ACK']._serialized_start=187
  _globals['_ACK']._serialized_end=209
  _globals['_EVENTSERVICE']._serialized_start=211
  _globals['_EVENTSERVICE']._serialized_end=266
# @@protoc_insertion_point(module_scope)
